---
- name: create 2 instances
  hosts: localhost
  gather_facts: False
  vars:
    keypair: galkey
    instance_type: t2.micro
    security_group: galesecgrp
    image: ami-04932daa2567651e7
    region: eu-central-1
  tasks:
    - name: add 1st instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-0760a07b
        assign_public_ip: yes
      register: ec2

    - name: add 1st instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: buildserver
      loop: "{{ ec2.instances }}"

    - name: add 2nd instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-0760a07b
        assign_public_ip: yes
      register: ec2

    - name: add 2nd instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webserver
      loop: "{{ ec2.instances }}"

- name: build java project
  hosts: build
  become: yes

  roles:
    - dockerserver
    - buildserver

- name: deploy production boxfuse
  hosts: web
  become: yes

  roles:
    - dockerserver
    - webserver